"""remove has_certificates

Revision ID: 283d4a991526
Revises: 438c23808390
Create Date: 2026-06-06 22:43:29.728301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '283d4a991526'
down_revision = '438c23808390'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.drop_column('has_certificates')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_certificates', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
