"""Add inn, certificate_urls, subcategories

Revision ID: 438c23808390
Revises: 
Create Date: 2026-06-06 21:04:48.517256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '438c23808390'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inn', sa.String(length=12), nullable=True))
        batch_op.add_column(sa.Column('certificate_urls', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.drop_column('certificate_urls')
        batch_op.drop_column('inn')

    # ### end Alembic commands ###
