"""convert min_order_amount to numeric

Revision ID: a6dc60d46335
Revises: 283d4a991526
Create Date: 2026-06-06 23:09:01.690048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6dc60d46335'
down_revision = '283d4a991526'
branch_labels = None
depends_on = None


def upgrade():
    # Нормализуем данные: пустые строки → NULL, чтобыNumeric не упал
    op.execute("UPDATE suppliers SET min_order_amount = NULL WHERE min_order_amount = ''")
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.alter_column('min_order_amount',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.alter_column('min_order_amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###
